services:
  db:
    image: postgres:16
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
  scraper:
    build: .
    env_file: .env
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app
volumes:
  db-data:
